{{- if .Values.rule.httpRoute.enabled -}}
{{- $serviceName := include "thanos.rule.fullname" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thanos.labels" . | nindent 4 }}
    {{- with .Values.rule.httpRoute.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.rule.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.rule.httpRoute.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.rule.httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
  {{- if .Values.rule.httpRoute.rules }}
    {{- toYaml .Values.rule.httpRoute.rules | nindent 4 }}
  {{- else }}
    - backendRefs:
        - name: {{ $serviceName }}
          port: {{ .Values.rule.service.httpPort }}
  {{- end }}
{{- end }}
