autoscaling:
  enabled: true
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

podDisruptionBudget:
  enabled: true
  maxUnavailable: 1
  unhealthyPodEvictionPolicy: AlwaysAllow

caCerts:
  enabled: true
  secretName: ca-certs

ingress:
  enabled: true
  ingressClassName: test
  hosts:
    - plantuml.local
  tls:
    - hosts:
        - plantuml.local
      secretName: plantuml-tls

httpRoute:
  enabled: true
  parentRefs:
    - name: gateway
      namespace: gateway
  hostnames:
    - plantuml.local
